### ISSUE TITLE
Tutorial-IDs nutzen für RStudio Cloud

### ISSUE THREAD

**Issue by luk-brue** [statistik-lehre/rtutorials#37]
**Bitte beschreiben Sie das Problem, was Sie sehen**

Für RStudio Cloud brauchen die Tutorials alle noch im YAML-Header eine Tutorial-ID, damit der Fortschritt der Studis auch ordentlich gespeichert wird. Ohne ID wird der Fortschritt verloren, wenn das Projekt pausiert wird.

**Beschreiben Sie die Lösung, die Sie sich wünschen würden.**
Alle Tutorials sollten im YAML-Header eine Tutorial-ID und Versionsnummer bekommen. Genauere Informationen finden sich hier: [rstudio/learnr issue #656](https://github.com/rstudio/learnr/issues/656#issuecomment-1030693979)

**Beschreiben Sie Alternativen, die Sie bedacht haben.**
Alternativ können wir das auch nicht tun, weil nicht so viele RStudio Cloud nutzen glaube ich.

**Comment by luk-brue** [comment]
Exemplary YAML header:
```yaml
output: 
    learnr::tutorial:
      progressive: true
      allow_skip: true
tutorial:
      id: zentrale_tendenj
      version: 1 # change the version when you want to invalidate past progress
```

- [ ] add ID and version fields to all tutorials

**Comment by jeffreyohene** [comment]
heißt dies, dass man für jeden Tutorial einfach ein id und eine versionnummer eingeben muss? 

z.B. f. SkalenNiveau würde der YAML header nach einer Bearbeitung wie folgt aussehen:

```
---
title: "Skalenniveaus"
output:
  learnr::tutorial:
    language: de
    css: css/boxes.css
    fig_caption: no
tutorial:
    id: skalenniveaus.Rmd
    version: 1
runtime: shiny_prerendered
bibliography: ref.json
link-citations: TRUE
description: "Welche Skalen gibt es und wie werden sie in R repräsentiert?"
resource_files:
- css/boxes.css
---
```
